model: resnet101_attention_baseline
outputpath: experiments/resnet101_attention_baseline

dataset_base_path: /dssg/home/acct-stu/stu464/data/image_caption
load_img_to_memory: False
vocab_path: utils/vocab_set.pkl
embedding_dim: 300
attention_dim: 256
decoder_size: 256
sample_args:
    method: greed # 'greed' or 'beam'
train_args:
    batch_size: 128
    learning_rate: !!float 1e-3
    num_epochs: 45
    save_freq: 10
eval_args:
    batch_size: 1
scheduled_sampling: none
