augment:
  mode:
  - block_mixing
  n_samples: 8
data:
    feature: data/dev/feature.csv
    label: data/dev/label.csv
    class_indice_file: data/metadata/class_label_indices.txt
    stratified: True
dataloader_args:
    batch_size: 32
    num_workers: 1

optimizer:
    type: AdamW
    args:
        lr: 0.001

epochs: 100 
model:
    type: Crnn
    conv_block: res
    args: {
        n_channels: [32, 64, 128],
        pooling_sizes: [4, 4, 2],
        gru_layers: 3,
        dropout: 0.2
    }

outputpath: experiments/
