augment:
  mode:
#   - mixup
  - block_mixing
data:
    feature: data/dev/feature.csv
    label: data/dev/label.csv
    class_indice_file: data/metadata/class_label_indices.txt
    stratified: True
dataloader_args:
    batch_size: 32
    num_workers: 1

optimizer:
    type: AdamW
    args:
        lr: 0.001

epochs: 100
model:
    type: Crnn
    conv_block: res
    args: {
        n_channels: [16, 32, 64],
        pooling_sizes: [4, 2, 2],
        gru_layers: 2,
        dropout: 0.2
    }

outputpath: experiments/
# python run.py train_evaluate configs/baseline.yaml data/eval/feature.csv data/eval/label.csv conv_aug_d0.2_1 --window_size=25
