data:
    feature: data/dev/feature.csv
    label: data/dev/label.csv
    class_indice_file: data/metadata/class_label_indices.txt
    stratified: True
dataloader_args:
    batch_size: 32
    num_workers: 1

optimizer:
    type: AdamW
    args:
        lr: 0.001

epochs: 100 
model:
    type: Crnn
    args: {
        n_channels: [128, 128, 192],
        pooling_sizes: [8, 4, 2],
        gru_layers: 2,
        gru_hidden: 64,
        dropout: 0.2
    }

outputpath: experiments/
