augment:
  mode:
  - time_shift
  - spec_aug
  - mixup
data:
  class_indice_file: data/metadata/class_label_indices.txt
  feature: data/dev/feature.csv
  label: data/dev/label.csv
  stratified: true
dataloader_args:
  batch_size: 32
  num_workers: 1
early_stop: 7
epochs: 100
loss: BceLoss
model:
  args:
    dropout: 0.2
    gru_layers: 2
    n_channels:
    - 16
    - 32
    - 64
    pooling_sizes:
    - 4
    - 2
    - 2
  conv_block: res
  type: Crnn
num_workers: 2
optimizer:
  args:
    lr: 0.001
  type: AdamW
outputpath: experiments/
scheduler_args:
  factor: 0.1
  patience: 3
